name: cicd

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  LOCAL_DYNAMO_ENDPOINT: "http://dynamodb:8000"
  AWS_REGION: "us-east-1"
  AWS_ACCESS_KEY_ID: "test"
  AWS_SECRET_ACCESS_KEY: "test"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 20.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker
#        run: docker-compose -f "docker-compose.yml" up -d --build
        run: docker-compose -f "docker-compose.yml" up dynamodb -d
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
      - name: Tear down
        if: always()
        run: docker-compose -f "docker-compose.yml" down

